### ISSUE TITLE
Marketplace search improvements

### ISSUE THREAD

**Issue by isidorn** [microsoft/vsmarketplace#154]
Hi VS Code PM here 👋 

I understand that there are already search issues opened in this repository, however I wanted to have one super issue which has all the items linked.
Improving search is the **number one** thing we would want for the Marketplace team to improve 💯 

If needed we can provide many more examples where search can be improved, but here's a list of issues to start. These examples are mostly from the Extensions view in VS Code which uses Marketplace search API.

- [x] microsoft/vsmarketplace#20
- [x] microsoft/vsmarketplace#68
- [x] microsoft/vsmarketplace#71
- [ ] microsoft/vsmarketplace#105
- [x] microsoft/vsmarketplace#107
- [x] microsoft/vsmarketplace#113
- [x] microsoft/vscode#151192
- [x] microsoft/vscode#42890
- [x] microsoft/vscode#73182
- [ ] microsoft/vscode#106418
- [x] microsoft/vscode#102193
- [x] microsoft/vscode#29779
- [x] microsoft/vscode#51207
- [x] microsoft/vscode#69810
- [x] Search with multiple words is sub-optimal https://github.com/microsoft/vsmarketplace/issues/154#issuecomment-1146212237
- [ ] https://github.com/microsoft/vsmarketplace/issues/413
- [x] microsoft/vsmarketplace#506

**Comment by jeff-hykin** [comment]
As one of the last people who commented on one of the main downstream issues 2 years ago: I'm really glad to see this being opened! 👍

**Comment by christianshay** [comment]
There are special characters (for example "/")  that are not needed and not documented that are messing up the tags.

This tag link is bringing up any extension that includes "PL" or "SQL" instead of those tagged "PL/SQL":
https://marketplace.visualstudio.com/search?term=tag%3APL%2FSQL&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by isidorn** [comment]
One more example:

![image](https://user-images.githubusercontent.com/1926584/159536309-30a4d471-2a29-4b95-b5f0-eb6f92787ae2.png)

**Comment by prashantvc** [comment]
We at VS Marketplace started the work to improve the search relevancy.
As part of this effort, we need your help to curate the search results to define baseline KPI

## How can you help?

1. Open VS Code or visit <https://marketplace.visualstudio.com/search?target=VSCode>
2. Search for your favourite extension
3. Share the search term and results you want to see.
   The Order of search results, missing results, and any results that shouldn't appear
4. Justification for No. 3 (eg: Why do you want to see certain results on the top or don't want to see)

You can share screenshots, text files, or add comment on this issue here

**Comment by jeff-hykin** [comment]
There's lots of examples from [previous posts](https://github.com/microsoft/vscode/issues/42890) that are still unfixed but sure I'll oblige and redo the search/screenshots


## Example 1
`Prolog Syntax`
<img width="439" alt="Screen Shot 2022-05-16 at 3 29 28 PM" src="https://user-images.githubusercontent.com/17692058/168679833-4b494db0-b4ef-4ffd-b140-c2ba8d485e81.png">

### Want to see & Justification

(The "Prolog" extension being at the top is fine)

1. My C++ syntax extension shouldn't be the 2nd option
2. A theme called "syntax" shouldn't be the 3rd option
3. My "Better Prolog Syntax" extension has
- a title with 100% of the search query
- keywords that match 100% of the search query
- been updated more recently
- and isn't being drug-down by missing or low ratings (5/5 stars)

Me wanting the the "Prolog Language" extension higher needs more justification though:

# Justification/Expected Feature: Inverse Word Importance 

If someone searches for "Code Entschuldigung" the results shouldn't be the most-popular extension with "Code" in the name;  thousands of extensions have "Code" in the name. Same with "Prolog Syntax". 

The equation is simple:
- How many times does a word appear across all extensions?
    - terms like "Language", "Code", "Syntax" are extremely common
    - a term "Prolog" or "Entschuldigung" is not
- Use Bayes Rule; inversely weight a word based on how common it is
- If an both the search and an extension have a very niche word in them that means the extension is **highly** relevant to the result 

I mean come on this is search-101 methodology

## Example 2
`Prolog Language`
<img width="464" alt="Screen Shot 2022-05-16 at 3 45 22 PM" src="https://user-images.githubusercontent.com/17692058/168679948-35b33546-86a4-494a-a5ac-bf72fa6a4f51.png">

My C++ syntax extension shouldn't be the 2nd option, and a theme called "syntax" shouldn't be the 3rd option, when my Prolog extension contains both an exact keyword and exact title match (and has been updated more recently, and has 5/5 start rating)


### Want to see

The one with arrow above Angular

### Justification: Negative Relevance

- If an extension title contains niche topics (high Bayes score) like "Japanese" and "Angular" that are NOT in the search, that should be penalty.<br>=> If someone was searching for Angular or Japanese they would type "Angular" or "Japanese" not "Prolog"

## Example 3
`code eol`
<img width="652" alt="Screen Shot 2022-05-16 at 3 33 41 PM" src="https://user-images.githubusercontent.com/17692058/168683311-bc8ff2ca-2209-4bf3-bb61-95e0365f4bf9.png">

(Keywords of the "Code-eol (Line Endings)" extension)
<img width="204" alt="Screen Shot 2022-05-16 at 3 34 50 PM" src="https://user-images.githubusercontent.com/17692058/168679109-a40c591f-6dbc-42b0-97a7-c390dfbc1275.png">

### Want to see

I'm going to assume the reader is intelligent and gets the idea.




As a side note I would expect word2vec similarity metrics, but I think VS Code Marketplace needs to start with the basics before I can request that.

**Comment by prashantvc** [comment]
@jeff-hykin Thanks a lot for taking time to write up a detailed answer. We are doing data driven, and iterative process to improve the search relevancy. Yes, we are starting with basics; you can expect better tokanisation and word2vec will eventually make into the marketpalce

**Comment by lramos15** [comment]
Here's a gif of searching for `Azure Repos`. I need to type the full name before it is even in view.
![Recording 2022-06-03 at 12 09 58](https://user-images.githubusercontent.com/4544166/171918024-9f0a7fd8-b559-4d90-8ffb-b875a72e4a28.gif)

**Comment by isidorn** [comment]
@lramos15 thanks for sharing this. 
@SaiKanth007 another great example of how scoring for multiple words is not good now.

**Comment by anangaur** [comment]
IMO, this could be ab issue of treating multiple forms of a word as different keywords. May be using a [stemmer ](https://towardsdatascience.com/stemming-of-words-in-natural-language-processing-what-is-it-41a33e8996e2) would help here?
For example,
`send`, `sending`, `sent` should all be stemmed as a common keyword `send`. If we apply this during tokenization of extension keywords as search query keywords, the above problem would be solved.

**Comment by anangaur** [comment]
@isidorn , this is a great list. @prashantvc , can we categorize the list into categories?

| Category | Issue | Comments |
|:-- | :-- |:-- |
| Bug | Extensions filter for publisher should be exact [vscode#151192](https://github.com/microsoft/vscode/issues/151192) | |
| Bug | Default to AND rather than OR in marketplace search [vscode#51207](https://github.com/microsoft/vscode/issues/51207)||
| Feature | Advanced extension search (for example excluding certain words) #20 ||
| Feature | Advanced extension search (for example excluding certain category) #20 ||
| Relevance | ||
| Tokenization ||
.
.
.

**Comment by isidorn** [comment]
Another example: search for Latex. The 2nd result should be first (much better quality, rating, install count, freshness)
![Screenshot 2022-06-12 at 13 58 16](https://user-images.githubusercontent.com/1926584/173232104-2fbe5d4e-df22-494e-b182-e75ac775dafc.png)

**Comment by prashantvc** [comment]
> Another example: search for Latex. The 2nd result should be first (much better quality, rating, install count, freshness)

Shouldn't the exact match be on the top? 2nd result has better metrics, but it is not too far away.

**Comment by isidorn** [comment]
@prashantvc by typing "latex" user wants to use latex, we should offer the best extension for this.
The same reason is when you type "vscode extension latex" in google you get the LaTeX Workshop, and not the other one.

Same example for "rust"

**Comment by jeff-hykin** [comment]
> The 2nd result should be first (much better quality, rating)

I would strongly disagree. I dont think anybody is having a hard time finding popular extensions like Latex workshop, rather the opposite; it's very hard to find the exact matches to excellent-but-unpopular extensions. 

Both have 5 stars and decent quality, but the first is actually matches what the user searched for. I'd rather it return what I searched instead of what's popular and kinda related to the search.

**Comment by isidorn** [comment]
Here’s an example that a vscode team member ran into. Search for "vscode selfhost test". The extension [“VS Code Selfhost Test Provider”](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-selfhost-test-provider) appears around position 50 I would guess (need to scroll down a bit), and before it there are 10 or more “test” extensions that I guess people used to test that they can publish :shrug:. Tweaking the query to "vscode selfhost test provider" still doesn’t show it in a top spot

![image](https://user-images.githubusercontent.com/1926584/173777302-76a7fc56-f121-4743-9758-0def209ca577.png)

**Comment by Tyriar** [comment]
I adding "Image Editor" despite really not wanted to because search wasn't smart enough to figure out Luna Paint is the only full blown image editor (see https://github.com/microsoft/vsmarketplace/issues/71), it contains from "edit images" in the package.json description and more keywords in the readme content.

![image](https://user-images.githubusercontent.com/2193314/173818836-4dfbc846-4641-48ad-abff-19d08610c840.png)

Similar bad examples, editor config and edit csv are high on both even though it doesn't seem to contain the word image?

![image](https://user-images.githubusercontent.com/2193314/173818900-93dc39c6-6ca8-4c51-aca5-31f9cbb67555.png)
![image](https://user-images.githubusercontent.com/2193314/173818936-b7856da3-6545-49a8-8c7d-89486609c69a.png)

**Comment by jeff-hykin** [comment]
> For short queries like 5, 6 characters exact match might not matter so much. So it should ideally be a linear increase per query length of how the \"exactness\" of the match is weighted.

I think changing the weight makes sense, but I think using number of characters would be problematic and easy to fix. Going back to Bayes, the word "Latex" would be super common, so I would agree exact match should be deprioritized with that in mind. But on the opposite side, if I search for "Mario" (very rare) and "visual studio code" (very common) I would expect Mario to prioritize an exact match while  "visual studio code" could prioritize popularity

**Comment by vadimcn** [comment]
This whole thing looks like a classical document retrieval problem, for which [TF-IDF](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) (basically what @jeff-hykin had described above) is the go-to approach.   This should cover all basics, and you can add rank boosting based on popularity on top of that.

I would also recommend talking to someone in Bing, they've been solving similar problems for a couple of decades by now.

**Comment by isidorn** [comment]
Good points. Thanks to both!

**Comment by RandomFractals** [comment]
> We at VS Marketplace started the work to improve the search relevancy. As part of this effort, we need your help to curate the search results to define baseline KPI
> 
> ## How can you help?
> 1. Visit https://extensions.ms/
> 2. Search for an extension (any of your favourite extensions)
> 3. Observe the search results, do they make sense?
> 4. Rearrange results, you can drag and drop, any item need to be on the top? Ranked lower
> 5. Fill in the feedback, rational behind the rearranging the results
> 6. Hit submit and repeat for different search terms

@prashantvc and @isidorn: how is this new extensions reranking page being used in improving extension search results by the marketplace team?

I tried and moved the [Pivotal Concourse CI Pipeline Editor](https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-concourse) down the recommended extensions list when searching for `image editor` because it has nothing to do with image editing and provides no such capabilites.

However, as an extension developer, I have some questions and concerns about this under the radar tool:

1. Do you use as part of some ML pipeline to improve search results in marketplace?
2. Should not you have some user authentication and validation when users of that page rearrange extensions to improve your search results?
3. Should not you add keywords, categories, and a link to the extension hover card to display full extension info summary and link to the extension in marketplace?
4. What guards to you have in place for that page to prevent someone scripting and upvoting their extensions? I've seen that happen with Svg Preview before as an example.

**Comment by codedChaos** [comment]
Just commenting to remind myself to research and elaborate in the morning but has anyone mentioned, or created an issue around the inefficacy of using multiple sort filters in a search?

In my years of VS Code extension searches, I typically have tried to improve results by using two sorting metrics. My biggest example is usually something like this: 
 
```
thing-i-want @sort:rating @sort:ratingcount
```  

or  

```
thing-i-want @sort:rating @sort:downloads
```  

I do this because simply sorting by rating returns plenty of 5-star extensions with only one to five actual reviews, which means diddly-squat to me. I want ratings over a 4 with at least a couple dozen reviewers/raters. 

I suspect the sort function is not stable when using multiple sort filters, but I'll be to do more testing to prove this.

Has anyone else noticed this or is it just me?

**Comment by isidorn** [comment]
@codedChaos this is great feedback. fyi @SaiKanth007 @kj0171

**Comment by tamuratak** [comment]
Hi, I am one of LaTeX Workshop's maintainers.

When searching a word `tex`, the extension's rank is ridiculously low. The word `tex` is set as a keyword in `package.json`. Users tend to use `tex` as the same term as `latex` although they are different.

- https://github.com/James-Yu/LaTeX-Workshop/blob/0b003ecb513de14b4e2667b9ecb8e9908af39eda/package.json#L25

We can say the same thing to `ms-python.python`. When searching `django`, the extension's rank is low although `django` is set as a keyword in `package.json`.

- https://github.com/microsoft/vscode-python/blob/830cbe717c534a8182bf7533ad80407a94180452/package.json#L47



![Screen Shot 2022-08-17 at 10 43 21-fullpage](https://user-images.githubusercontent.com/10665499/185016215-5b4277f2-2509-40b3-ac88-82dbeb27a7ad.png)

**Comment by isidorn** [comment]
@tamuratak great feedback!
fyi @SaiKanth007 @kj0171

**Comment by isidorn** [comment]
Another bad search and result

The first result should be the "Live Share" extension which is not even a result here.

<img width="324" alt="Screenshot 2022-09-01 at 21 42 01" src="https://user-images.githubusercontent.com/1926584/187998926-cf8ca1e6-4a26-44a4-8472-8c777881b7dd.png">

**Comment by benibenj** [comment]
Here a comparison between the old and new Search results. I entered the exact same name of an extension. In the old version it shows up at second place which is fine (I think it should be first on exact match). In the new version it's placed a lot further down! 

Old results:
<img src="https://user-images.githubusercontent.com/44439583/192996345-2e9fb30c-0115-4872-bd9b-6ca54cf1f647.png" width=35%>

New results:
<img src="https://user-images.githubusercontent.com/44439583/192996342-a7b5217b-7292-48f2-8b9b-be620a807859.png" width=35%>

**Comment by prashantvc** [comment]
@benibenj thanks for a lot for the report! We will investigate it.
But generally, how do you like the new search service?

**Comment by benibenj** [comment]
It seems that smaller extensions (less downloads) are harder to find if they have multiple words in their name (Python C++ Debugger for example).

**Comment by hediet** [comment]
`GitLens` should be first when searching for `Git Lens`:

![image](https://user-images.githubusercontent.com/2931520/195666100-53191969-3509-4f6a-8217-7d09623f1f54.png)

`Version Lens` should be below, as it does not even mention git.

**Comment by kj0171** [comment]
We have done some bug fixes and improvements on the marketplace search service. The changes are live in vscode insider. Do try them out and share feedback :)

https://user-images.githubusercontent.com/25655940/196911597-ec51bfce-00a0-4771-b8f2-d2fdd040300c.mp4

**Comment by hediet** [comment]
Nice work on the update!

However, I find this problematic:

![image](https://user-images.githubusercontent.com/2931520/197036073-5b4e852b-8a08-4ab9-aedc-3cdbd6e6181e.png)

The `GitLens` extension does not show up here.

**Comment by isidorn** [comment]
@hediet thanks for the feedback, we are looking into this exact case. The issue is that we are doing prefix matching instead of fuzzy matching.

**Comment by lramos15** [comment]
Maybe an edge case but when searching by publisher `i.e. Matt Bierner` the top result doesn't make sense and the third result is a bit of a weaker match I'd say.
<img width="584" alt="image" src="https://user-images.githubusercontent.com/4544166/197794696-c0bbc7f0-395a-4a6d-93d7-8a3ddbfe7958.png">

**Comment by isidorn** [comment]
@lramos15 good catch, thanks for reporting this.
@SaiKanth007 @kj0171 let's double check this one once we do the improvements we agreed on.

**Comment by kj0171** [comment]
> Simple filtering options for statistical properties such as last updated date, download count, verification status, etc. Preferably multiple of such filters could be applied simultaneously.
> 
> This would, for example, allow me to display only extensions updated within the last 30 days, with a download count of at least 2500, and only by verified publishers.
> 
> This data is already available to the marketplace search results page (took a quick peek at the devtools network panel), so why not use it?

Thanks for the feedback. We are aware of this. Will try to address this in near future.

**Comment by kj0171** [comment]
We have rolled out search enhancements (Details here: https://github.com/microsoft/vsmarketplace/issues/154#issuecomment-1285224069). 

Please share feedback and reopen if necessary.

**Comment by isidorn** [comment]
Thanks @kj0171 

To clarify, most of the improvements can be seen in VS Code Insiders.
While we plan to have these improvements in VS Code Stable soon.
Try them out in VS Code Insiders and let us know what you think.

**Comment by alefragnani** [comment]
Just noticed something on **Insiders** release that could lead to an impersonating issue discussed here https://vscode-dev-community.slack.com/archives/C74CB59NE/p1673358662096609, based on a post in  https://blog.aquasec.com/can-you-trust-your-vscode-extensions

**_The marketplace search does not respect exact match if you use the `publisher` field._** 

I search for an extension, clicked in the publisher name to see other extensions of that publisher (myself), but the new search also returns extensions from authors with similar names.

![image](https://user-images.githubusercontent.com/3781424/211622292-ecf9e1e7-4723-4399-a574-7e79398c8259.png)


Based on [this comment](https://github.com/microsoft/vscode/issues/151192#issuecomment-1293059902) it seems only _well-known publishers_ are handled, but I would argue that this change should be revisited.

Also, if you _misstype_ the search, using `publisher:"microsoft` instead (yes, just missing the final double quotes), the result is not good at all. This error, on the other hand, happens on both, Stable and Insiders releases.

![image](https://user-images.githubusercontent.com/3781424/211622152-066ac7e6-5e8d-40d6-97b3-2a8212fd43ca.png)

Thank you

**Comment by kj0171** [comment]
> Just noticed something on **Insiders** release that could lead to an impersonating issue discussed here https://vscode-dev-community.slack.com/archives/C74CB59NE/p1673358662096609, based on a post in https://blog.aquasec.com/can-you-trust-your-vscode-extensions
> 
> **_The marketplace search does not respect exact match if you use the `publisher` field._**
> 
> I search for an extension, clicked in the publisher name to see other extensions of that publisher (myself), but the new search also returns extensions from authors with similar names.
> 
> ![image](https://user-images.githubusercontent.com/3781424/211622292-ecf9e1e7-4723-4399-a574-7e79398c8259.png)
> 
> Based on [this comment](https://github.com/microsoft/vscode/issues/151192#issuecomment-1293059902) it seems only _well-known publishers_ are handled, but I would argue that this change should be revisited.
> 
> Also, if you _misstype_ the search, using `publisher:"microsoft` instead (yes, just missing the final double quotes), the result is not good at all. This error, on the other hand, happens on both, Stable and Insiders releases.
> 
> ![image](https://user-images.githubusercontent.com/3781424/211622152-066ac7e6-5e8d-40d6-97b3-2a8212fd43ca.png)
> 
> Thank you

Thank you for pointing out the issue. For some reason, we aren't able to take this fix forward. We are aware of this issue and are working towards this. It will soon be fixed. We will keep you updated.

**Comment by prashantvc** [comment]
We deployed the search improvements. 
**Note:** This is an ongoing effort, and more improvements will follow. We appriciate if you have any feedback for the team

You will start seeing more relevant results, and support for following features:

- Inclusion and Exclusion (+, -)
- Enforce the search results to include or exclude search terms
- Special Word Support (AND, OR, NOT)
- Overall relevancy improvements

_Light Theme - Previous Search
Dark Theme - New and Improved Search_

**Multi-word search**
![image](https://user-images.githubusercontent.com/328076/211777099-b429394c-db2d-42ab-9120-7a91ce12a3bf.png)

 
![Screenshot 2023-01-11 at 15 37 17](https://user-images.githubusercontent.com/328076/211777885-e28a7850-e15e-45c2-b9a1-54c406d80735.png)

 
**AND/OR**
You can now use AND/OR operation with multiword searches 
 
![Screenshot 2023-01-11 at 15 39 04](https://user-images.githubusercontent.com/328076/211778054-ca2cbf95-07d5-4e94-9d05-8106331190c1.png)


**NOT**
Exclude unwanted search terms
![Screenshot 2023-01-11 at 15 39 39](https://user-images.githubusercontent.com/328076/211778158-a116d467-304f-4520-88e8-4a5a9a053781.png)

**Comment by prashantvc** [comment]
> The marketplace search does not respect exact match if you use the publisher field.

@alefragnani This is quite an unique problem, thanks a lot for reporting. There are two opinions within the team/VS Code users.
We are still figuring out the intent behind the query. Did user mean to apply a filter? Did they try search extensions by publisher name!? It may take awhile conclude this.

The missing double quote can be handled better, it's on our list to fix it.

**Comment by prashantvc** [comment]
Hey All,

We have deployed (7th Feb) number of changes to the _VS Code Insiders_ improving relevancy, especially for multi-word searches and overrall search experience. The improvements will make their way into VS Code Stable in couple of weeks

Please give it try and let us know what you think. We will continue to work on improving search in VS Code as well as in the Marketplace; your continued support and feedback will help us make it better for the community. 

Thank you all for participating in the discusstion. Please feel free to leave comments or contact me directly, we can chat about ideas and possible improvents ([Booking Link](https://outlook.office.com/bookwithme/me?ep=option&login_hint=prchol@microsoft.com))

I am closing this issue, and continue discussion in the open issues listed in the description

**Comment by isidorn** [comment]
I created this follow up issue to make sure @alefragnani publisher bug is still captured
https://github.com/microsoft/vsmarketplace/issues/580

@SaiKanth007 mentioned to me that this should be fixed end of March.

**Comment by gerroon** [comment]
This is not working for me. Is this implemented?

`@enabled NOT @category:"themes" `
